default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  port: 5433

development:
  <<: *default
  database: score_keeper_development

test:
  <<: *default
  database: score_keeper_test

production:
  <<: *default
  database: score_keeper_production
